/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightsoutmoorebatard;

import java.util.Random;

/**
 *
 * @author Administrateur
 */
public class interfaceLightsOut extends javax.swing.JFrame {
    private Grille grilleInterface = new Grille();
    /**
     * Creates new form interfaceLightsOut
     */
    public interfaceLightsOut() {
        initComponents();
        //boardPage.setVisible(false);
        for (int i = 4; i >= 0; i--){
            for(int j =0; j<5; j++){
                celluleGraph cellGraph = new celluleGraph(grilleInterface.retournerCase(i, j));
                boardPage.add(cellGraph);
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        start = new javax.swing.JButton();
        boardPage = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startPage.setBackground(new java.awt.Color(255, 204, 204));
        startPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Débuter une partie: ");
        startPage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 6, -1, 20));

        jLabel2.setText("prénom:");
        startPage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        startPage.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 110, -1));

        start.setText("Démarrer");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        startPage.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        getContentPane().add(startPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 420, 140));

        boardPage.setBackground(new java.awt.Color(0, 0, 0));
        boardPage.setPreferredSize(new java.awt.Dimension(340, 340));
        boardPage.setLayout(new java.awt.GridLayout(5, 5));
        getContentPane().add(boardPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 360, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        String nom = name.toString();
        Joueur joueur= new Joueur(nom);
        setOn();
        boardPage.repaint();
        
        cellGraph.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        CelluleDeGrille c = cellGraph2.celluleAssociee;
                        if (c.getJetonCourant() == null) {
                            infoMessage.setText("la case est vide");
                        }
                        if (c.getJetonCourant().lireCouleur().equals(gameBis.getJoueurCourant().getCouleur())) {
                            infoMessage.setText("Vous avez bien récupérer un de vos jeton");
                            gameBis.getJoueurCourant().ajouterJeton(c.recupererJeton());
                            changeJoueurCourant();
                        }else{
                            if(gameBis.getJoueurCourant().getNbDesintegrateurs() >0){
                                infoMessage.setText("Vous avez bien désintégré un jeton adverse");
                                c.supprimerJeton();
                                gameBis.getJoueurCourant().utiliserDesintegrateur();
                                changeJoueurCourant();
                            }else{
                                infoMessage.setText("Vous n'avez pas de desintegrateurs");
                            }
                            
                            
                        }
                    }
                });
        
        
    }//GEN-LAST:event_startActionPerformed
    
    
    
    
    public void setOn(){
        Random r = new Random();
        for(int i = 0; i < 5; i++){
            int ligne = r.nextInt(0, 5);
            int colonne = r.nextInt(0, 5);
            if (grilleInterface.caseAllumer(ligne, colonne) == false){
                grilleInterface.allumerCase(ligne, colonne);                
            }else{
                i -=1;
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceLightsOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceLightsOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceLightsOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceLightsOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaceLightsOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField name;
    private javax.swing.JButton start;
    private javax.swing.JPanel startPage;
    // End of variables declaration//GEN-END:variables
}
